In [113]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [114]:
df=pd.read_csv('/content/social_network.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [115]:
df=df.iloc[:,1:]

In [116]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [117]:
encoder=LabelEncoder()

In [118]:
df['Gender']=encoder.fit_transform(df['Gender'])

In [119]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [120]:
Scalar=StandardScaler()

In [121]:
x=df.iloc[:,0:-1]

In [122]:
x=Scalar.fit_transform(x)

In [123]:
x.shape

(400, 3)

In [124]:
y=df.iloc[:,-1]

In [125]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [126]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [127]:
knn=KNeighborsClassifier(n_neighbors=5)

In [128]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [129]:
y_pred=knn.predict(x_test)

In [130]:
accuracy_score(y_test,y_pred)

0.95

In [131]:
print(x_train.shape)
print(x_test.shape)

(320, 3)
(80, 3)

In [132]:
from scipy.spatial import distance
from collections import Counter
class MyKnn:
  def __init__(self,k=5):
    self.n_neighbors=k
    self.x_train=None
    self.y_train=None

  def fit(self,x_train,y_train):
    self.x_train=x_train
    self.y_train=y_train

  def calculate_distance(self,point1,point2):
    return float(np.linalg.norm(point1-point2))

  def predict(self, x_test):
    y_pred= []

    for i in x_test:
        distances = []

        # calculate distance with every training point
        for j in self.x_train:
            distances.append(self.calculate_distance(i, j))
        n_neighbors=sorted(list(enumerate(distances)),key=lambda x:x[1])[0:self.n_neighbors]
        label=self.majority_count(n_neighbors)
        y_pred.append(label)

    return y_pred

  def majority_count(self,n_neighbors):
    votes=[]
    for i in n_neighbors:
      votes.append(int(self.y_train.iloc[i[0]]))
    votes=Counter(votes)
    return votes.most_common()[0][0]

In [133]:
myclassifier=MyKnn(k=5)

In [134]:
myclassifier.fit(x_train,y_train)

In [135]:
y_pred=myclassifier.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.95