In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("/content/salary_data 2.csv")

In [4]:
df.head()

   age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

In [5]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [7]:
X.head()

   age  experience
0   25           1
1   30           3
2   47           2
3   32           5
4   43          10

In [9]:
y.head()

0    30450
1    35670
2    31580
3    40130
4    47830
Name: income, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [24]:
X.shape

(20, 2)

In [25]:
y.shape

(20,)

In [26]:
x_train.shape

(16, 2)

In [27]:
y_train.shape

(16,)

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lr=LinearRegression()

In [30]:
lr.fit(x_train,y_train)

LinearRegression()

In [46]:
coef=lr.coef_
coef

array([-102.88197553, 2191.86022152])

In [42]:
intercept=lr.intercept_

In [34]:
y_pred = lr.predict(x_test)

In [44]:
y_pred

array([36843.22672444, 48934.22956284, 46639.48736579, 31059.36312867])

In [49]:
np.dot(x_test.iloc[0].values,coef)+intercept

np.float64(36843.22672444271)

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 1071.5766954370147
MSE 1901454.8827072307
R2 score 0.9579002513351036

In [53]:
r2=r2_score(y_test,y_pred)
adjusted_r2=1-((1-r2)*(20-1)/(20-1-2))

In [54]:
print('adjusted_r2 ',adjusted_r2)

adjusted_r2  0.9529473397274687