In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/salary_data 2.csv")

In [3]:
df.head()

   age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

In [4]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [7]:
X.head()

   age  experience
0   25           1
1   30           3
2   47           2
3   32           5
4   43          10

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [9]:
class MyLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)


        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [11]:
lr = MyLR()

In [14]:
lr.fit(x_train,y_train)

In [16]:
y_pred = lr.predict(x_test)

In [17]:
lr.coef_

array([-102.88197553, 2191.86022152])

In [18]:
lr.intercept_

np.float64(31439.552295348745)